sudo: false

language: haskell

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.stack

env:
- STACK_FLAGS=--system-ghc

matrix:
  include:
  - env: BUILD=nightly
    ghc: 8.2.2
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=lts-10
    ghc: 8.2.2
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=lts-9
    ghc: 8.0.2
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=lts-8
    ghc: 8.0.2
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=lint
    ghc: 8.2.2
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=pretty
    ghc: 8.2.2
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=sdist
    ghc: 8.2.2
    addons: {apt: {packages: [libgmp-dev]}}

before_install:
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- |
  set -ex
  mkdir -p ~/.local/bin
  travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  set +ex

install:
- |
  set -ex
  stack --system-ghc setup --upgrade-cabal && stack --system-ghc install --pedantic
  set +ex

script:
- |
  set -ex
  case "$BUILD" in
    lts-*)
      RESOLVER=$BUILD make test
      ;;
    nightly)
      RESOLVER=$BUILD make test
      ;;
    lint)
      make lint
      ;;
    pretty)
      make format
      ;;
    sdist)
      make test-sdist
      ;;
  esac
  set +ex

notifications:
  email: false
